### ISSUE TITLE
Required admin approval when launch UEVR

### ISSUE THREAD

**Issue by peteostro** [Raicuparta/rai-pal#106]
When using steam link and trying to launch UEVR using Rai Pal (to get the profile to work) I can not see the admin dialogue popup, so I can’t approve it. Is there anyway around this?

**Comment by Raicuparta** [comment]
And this doesn't happen when you launch UEVR.exe without Rai Pal?

**Comment by Raicuparta** [comment]
I'm closing this for now since it doesn't seem related to Rai Pal, but let me know if I'm missing something and I'll reopen.

**Comment by peteostro** [comment]
> And this doesn't happen when you launch UEVR.exe without Rai Pal?

no when launch UEVR.exe on its own the windows authorization popup (UAC) does not happen. Only when launching from Rai Pal

**Comment by Raicuparta** [comment]
Ah I see the problem. I was under the impression that UEVR needed to run as admin, but I misremembered, it's only for "some executables" (probably windows store / pc xbox ones).

UEVR does have a "restart as administrator" button in the UEVR app. If you start the UEVR exe manually and press that button, do you still have the same problem?

I'll reopen this issue while I think about what to do.

**Comment by peteostro** [comment]
Thanks, I’ll give that a try but I’m assuming it would. If I use virtual desktop I can click the UAC prompt to let it go through but steamlink does not have that ability, and there a lot of people using steamlink on Q3 as its free and works well.

**Comment by Raicuparta** [comment]
Alright, I asked around a bit and it seems that running as admin is very rarely needed. So I'll remove the privileges prompt starting in Rai Pal 0.3.6, and if it ends up being needed I'll add an option for it.

**Comment by Raicuparta** [comment]
Reopening this, had to revert the change because I broken UEVR auto-injection. Will try to fix it properly later.
