### ISSUE TITLE
Make it clearer that Epic and GOG are only supported on the Installed Games tab for now

### ISSUE THREAD

**Issue by Raicuparta** [Raicuparta/rai-pal#108]

**Comment by Foebik** [comment]
Any chance we can see a list of games that are not installed yet like we do for Steam?

**Comment by Raicuparta** [comment]
> Any chance we can see a list of games that are not installed yet like we do for Steam?

Not sure. Main problem will be detecting the engine for any games that aren't on Steam. There's basically no way to do that across the board, we'll probably have to create some mapping of steam app ids to other providers, which will probably need a lot of manual work. Without detecting the engine, I think there's not much point in listing an owned game.
