### ISSUE TITLE
Auto launch game after launching UEVR?

### ISSUE THREAD

**Issue by Raicuparta** [Raicuparta/rai-pal#111]
Not sure if this could be problematic, should probably be an option

**Comment by drhouse** [comment]
There was a nice feature that has seemed to disappear from earlier versions of Rai-Pal:
1. I would click on a game e.g. GameA
2. GameA info window would open 
3. I'd click 'Run [UEVR version]', UEVR autofills in "Waiting for 'GameA.exe'
4. then I'd click 'Start GameA' 
up to this point, it still works the same as always

The way it is now, one then has to manually find the game process in the scroll list and then press the 'Waiting for GameA' button to inject. But, here's what it used to do: UEVR would immediately auto-detect GameA as soon as it had started running, and automatically inject into GameA - basically doing everything itself.

**Comment by Raicuparta** [comment]
@drhouse that was a bug, already fixed in the latest versions.

**Comment by drhouse** [comment]
ok, good job, great app 👍
