### ISSUE TITLE
Launch UEVR for a specific game, so you don't need to select the game process in the UEVR menu (not working for me)

### ISSUE THREAD

**Issue by nabel0** [Raicuparta/rai-pal#128]
if i klick the button for a specific game to run UEVR it starts UEVR in the mode "waiting for the_specific_game.exe":

<img width="1117" alt="kp3cDl5fWp" src="https://github.com/Raicuparta/rai-pal/assets/50377455/1d9e3337-d8a5-4d0e-8909-7c4449053e08">

So far so good.
But after i press the button to launch the game UEVR is not pickig up the game "process" and autoinjects.
It still says "waiting for blah_blah.exe":

![AbzuGame-Win64-Shipping_9Naww1AZ8y](https://github.com/Raicuparta/rai-pal/assets/50377455/cdd4d2e9-218a-4340-9f25-db992b12480a)

I have to select the game process manually in the list an then click the button "waiting for blah_blah.exe" to get it working:

![AbzuGame-Win64-Shipping_WUfwHs2lwg](https://github.com/Raicuparta/rai-pal/assets/50377455/ca752ded-38b2-48e4-a26e-79a2e4c61c70)

A couple versions back it was working automatic.

**Comment by Raicuparta** [comment]
Fixed in 0.3.8
