### ISSUE TITLE
Target boxes for mouse clicks off

### ISSUE THREAD

**Issue by Foebik** [Raicuparta/rai-pal#131]
The target boxes for the mouse clicks after update to 0.4.0 is no longer matching the graphics in the popup elements.

https://youtu.be/hc6suw7qEGA

**Comment by Foebik** [comment]
Just did some manually scrolling in the main window and everything shifted slightly and it now seems it is lined up now.

**Comment by Raicuparta** [comment]
Has this happened multiple times or just the once? No idea how I'd go about reproducing this

**Comment by Foebik** [comment]
It happened every time on everything after the first boot of the new version. But since I did that manually scroll and everything shifted, I haven't seen it again. I did noticed a difference in the window placement from the video to now as seen below. But honestly have no idea how or if you can reproduce this. If not, just close and toss into "weird" bucket. :) 

Video Image
![Then](https://github.com/Raicuparta/rai-pal/assets/6633492/05a8dbad-f434-4a67-bef0-738f89c1a83f)

And now
![Now](https://github.com/Raicuparta/rai-pal/assets/6633492/48b06d1a-dbc3-47f3-ae8d-efded4f46949)

**Comment by Raicuparta** [comment]
Actually managed to reproduce this accidentally. Might be related to the filter popup causing the whole window to be scrollable.
