### ISSUE TITLE
It's confusing that some games show in owned games tab but not in installed games tab

### ISSUE THREAD

**Issue by Monsair** [Raicuparta/rai-pal#141]
![Screenshot 2024-01-04 114225](https://github.com/Raicuparta/rai-pal/assets/40468443/29c694ab-a985-4ab6-b5d2-aaf7d67a2f02)
![Screenshot 2024-01-04 114145](https://github.com/Raicuparta/rai-pal/assets/40468443/f8f38df8-581d-47f4-affc-06a88b6a3c35)
![Screenshot 2024-01-04 114309](https://github.com/Raicuparta/rai-pal/assets/40468443/f93c374a-9b12-4160-bda5-b751d02c00fd)

**Comment by Raicuparta** [comment]
this is because the installed tab shows only games where engine is known, while owned tab shows all. i'll improve this later

**Comment by Raicuparta** [comment]
Fallen Order was a special case since it really wasn't being detected as Unreal when installed. I think it might be fixed in 0.6.1, but it also might not. Let me know.

**Comment by stoolzo** [comment]
Hi, just to let you know that Jedi fallen order still not shown in current release -

**Comment by Mace404** [comment]
The game 'Trail Out' is also not shown in the installed game list.
It shows up in Owned and also has a version number.
