### ISSUE TITLE
Can't install UUVR anymore

### ISSUE THREAD

**Issue by Dangahzone** [Raicuparta/rai-pal#142]
It appears the .4.0 update broke installing UUVR, It worked fine last night but upon trying all 3 updates today I get this now.
![dsa](https://github.com/Raicuparta/rai-pal/assets/119710571/a3607a0f-7f64-48af-8429-f5da873fe5f1)

**Comment by Raicuparta** [comment]
Strange, I'm not able to reproduce. Can you try an older verison of Rai Pal? Maybe 0.3.8 here? https://github.com/Raicuparta/rai-pal/releases/tag/v0.3.8 
Or whatever version worked for you before. Not sure what could have broken this, so figuring out exactly what version it broke would be helpful.

Just say no when it prompts to auto-update.

**Comment by Dangahzone** [comment]
Sorry yeah it works on 3.6 but not 3.8 and up

**Comment by Raicuparta** [comment]
Forgot to ask, would be useful if you could send me the full logs file after triggering that error a couple times. There's a button to open the logs folder in the settings tab.

**Comment by Dangahzone** [comment]
Here is a log from a fresh install of the newest version
[Rai Pal.log](https://github.com/Raicuparta/rai-pal/files/13835382/Rai.Pal.log)

**Comment by zymox** [comment]
Same error here (just localized to German in the log).
[Rai Pal.log](https://github.com/Raicuparta/rai-pal/files/13835525/Rai.Pal.log)

**Comment by zymox** [comment]
Actually the error doesn't seem to be put in the log, triggering it doesn't add any log line. 
The error shown in the log already appears when starting the program.

**Comment by deterministicj** [comment]
I helped narrow it down for Rai. It's between 0.3.7 and 0.3.8
