### ISSUE TITLE
where is the program installed on windows

### ISSUE THREAD

**Issue by peteostro** [Raicuparta/rai-pal#147]
using the newest version. i can no longer find the .exe on windows. its not in the start menu. its not in program files, where is it located?

**Comment by Raicuparta** [comment]
It's supposed to be at C:\Program Files\Rai Pal\Rai Pal.exe by default. If it's not there, your antivirus might have deleted it. There seems to be a false positive with some antivirus software right now.

**Comment by peteostro** [comment]
note this is after using the built in upgrader. To bring rai pal back i had to download new msi, run it. tell it to uninstall then run it again to install. then it adds the start menu shortcut

**Comment by Raicuparta** [comment]
Other people have reported Windows Defender being annoying about both Rai Pal and UEVR, so yeah might be it

**Comment by AveryLucas** [comment]
Yep can confirm same happened to me. I let it download the latest update and soon after, its gone

**Comment by Raicuparta** [comment]
This is almost definitely due to antivirus software such as Windows defender flagging Rai Pal, follow the issue at #145.
I'm releasing update 0.5.5 now, which hopefully helps, but it's hard to tell with these things.

**Comment by Raicuparta** [comment]
Closing this as it's most likely the antivirus thing and being tracked in #145
