### ISSUE TITLE
Enhancement Request - Not show Dedicated Servers

### ISSUE THREAD

**Issue by Foebik** [Raicuparta/rai-pal#152]
For the list of games shown that you own, can you have it ignore and not display the ones for dedicated servers? Some of these ones I have I dont even know what they are for and never added them myself but somehow they are in my list. 

I manually clean this up in my own list in Steam by hiding them. But the app also picks up all the ones I have hidden.

**Comment by Foebik** [comment]
Still pulling some dedicated servers.
![image](https://github.com/Raicuparta/rai-pal/assets/6633492/993ff164-be52-448d-bed8-ce59cea6ac5d)

**Comment by Raicuparta** [comment]
Those aren't properly marked as tools by the game dev/publisher on Steam.

**Comment by Foebik** [comment]
I dont know how these are being pulled up. Does Steam just automatically make these dedicated game servers available? As mentioned in another thread, maybe a way we could hide(delete) them ourselves would be a good fix for things that are showing up and not so easy to get rid of programmatically like these are.
