### ISSUE TITLE
Not showing in Installed list - STAR WARS Jedi Fallen Order

### ISSUE THREAD

**Issue by Foebik** [Raicuparta/rai-pal#153]
While the game STAR WARS Jedi Fallen Order shows in the "Owned" game list (until it is installed), once installed it does not appear in the installed list. In the owned list it shows it as being a viable game with a B rating.

**Comment by Raicuparta** [comment]
That means it's not being detected as an Unreal game. I'll have to look more closely at that game's file structure to see where it went wrong. Reference for my future self: https://steamdb.info/depot/1172381/

#149 would make this slightly better, might be implemented soon as a workaround for this kind of thing.

**Comment by Raicuparta** [comment]
Closing this one as being part of #154 instead
