### ISSUE TITLE
UEVR profiles

### ISSUE THREAD

**Issue by peteostro** [Raicuparta/rai-pal#156]
Right now it’s hard to find uevr profiles for games   Any way for Rai Pal to automatically launch UEVR with a recommended profile for the game you are launching?

**Comment by peteostro** [comment]
You can find profiles in the profiles tab of this Google sheet https://docs.google.com/spreadsheets/d/1ZcjCQwzPOltaRZnpYU5_HPihEDareZq_0Ww1DZQ4USw/edit#gid=1224938259

**Comment by Raicuparta** [comment]
That's in the plans, will happen once the flat2vr db is up and running

**Comment by Raicuparta** [comment]
Just realized this is a duplicate of #110
