### ISSUE TITLE
Add provider-specific "start" buttons to non-Steam installed games

### ISSUE THREAD

**Issue by keton** [Raicuparta/rai-pal#167]
Issue: some Epic games expect to talk to EGS launcher API to work properly. Launching .exe directly causes them to fail in various ways. 
When launched from `com.epicgames.launcher://` protocol URL they run fine.

Test cases:
* The Expanse: A Telltale Series will claim that no episodes are purchased
* Sackboy will spin forever on loading screen after intro cinematics

Those are reproducible even when just launching .exe from a folder.

**Comment by Raicuparta** [comment]
Related to #162, although that one is for owned games. I intend on doing this for any provider that makes it easy to do so. Will rename this issue to make it include other providers.
