### ISSUE TITLE
Pulls a game not in my list on Steam

### ISSUE THREAD

**Issue by Foebik** [Raicuparta/rai-pal#169]
I have a game called "Forge" that comes up in your list as a Steam game. Never heard of it, it doesn't actually have a store page anymore and is no where to be found in my Steam list (hidden or otherwise).

![image](https://github.com/Raicuparta/rai-pal/assets/6633492/dbcf6fbb-2d11-4aba-929b-644b4eb01f05)
![image](https://github.com/Raicuparta/rai-pal/assets/6633492/4d3b52fe-935a-4a3d-a19f-7eb55b0185c7)

**Comment by Raicuparta** [comment]
Have you tried the "fix list" button in the owned games tab? It guides you through resetting the cache. It might be you actually do have that game in your library, but it was just delisted by the publisher so it's been permanently hidden. I think the only way of checking for this would be by making an extra request per Steam game, which might make things a lot slower. Need to investigate a bit

**Comment by Raicuparta** [comment]
Also note that even though the store page doesn't exist, you can still install that game using the install button from Rai Pal. Steam will still let you install it that way, it will just not work since it was an online-only game.

**Comment by Raicuparta** [comment]
No clue, I have it in my list too and never heard of it. Rai Pal just pulls this stuff from the steam cache. Since this isn't really a bug I'll just close it in favor of #172
