### ISSUE TITLE
[Feature Request] Toggle for UEVR Nightly builds

### ISSUE THREAD

**Issue by Stunner1984** [Raicuparta/rai-pal#196]
Wondering if it would be possible to have a toggle for the UEVR Nightly builds? 

Maybe also the ability to have 2 separate launch buttons ( one stable, one nightly) to try both and experiment?

Thanks, love the work!

**Comment by Raicuparta** [comment]
The nightly zips not having all UEVR files makes it a bit annoying, means I need to add more specific functionality to support it.

**Comment by Stunner1984** [comment]
Ok thanks for the response, maybe something that Praydog can add/update on his end to make it easier on yours.

**Comment by Raicuparta** [comment]
OK maybe spoke too soon, that one is merged but there's still one thing left to do after that

**Comment by Stunner1984** [comment]
Awesome thanks much for the quick work!
