### ISSUE TITLE
Add option to hide demos

### ISSUE THREAD

**Issue by KeksNino** [Raicuparta/rai-pal#207]
Owned Games tab shows every demo game on steam.

**Comment by Raicuparta** [comment]
It only shows demo games you've added to your library at some point, not every demo on steam. Closing this as the subject is discussed in #203

**Comment by KeksNino** [comment]
Can i somehow disable this?

**Comment by Raicuparta** [comment]
Reopening since the other one is about a possible bug, this one is about hiding the actual demos
