### ISSUE TITLE
Failed to get game data from path

### ISSUE THREAD

**Issue by jadmanxxx** [Raicuparta/rai-pal#208]
i have install Guardians of the Galaxy frome epic store.

Rai-Pal not found the game. if i whant to add by hand i get error 

Failed to execute command: Failed to get game data from path `\\?\C:\Program Files\Epic Games\MarvelGOTG\retail\gotg.exe`

**Comment by Raicuparta** [comment]
That's just because that game doesn't use an engine that Rai Pal can do anything with. The error message could probably be clearer. Related to #141
