### ISSUE TITLE
Game detected as owned, but not in installed

### ISSUE THREAD

**Issue by DuckingMitch** [Raicuparta/rai-pal#215]
Game witch it released as unreal 4 and still shows that in the owned tab. Devs updated to 5.3.2. the game doesn't show up as installed, had to manually add game and it works great that way. Manual adding shows the correct 5.3.2.
Just reporting, no need for a fix as manual mode makes uevr work as intended.

**Comment by Raicuparta** [comment]
Some discussion about this in #141
