### ISSUE TITLE
Rai Pal can't detect any Steam games when using Steam Beta

### ISSUE THREAD

**Issue by Bassquake** [Raicuparta/rai-pal#222]
I used to have all my Steam games showing in the Installed games tab but now its only Epic ones. Filters are all checked.

Rai Pal 0.12.0 on Windows 10 22H2.

Fix List option didnt make a difference.

Attached log file.
[Rai Pal.log](https://github.com/user-attachments/files/16103097/Rai.Pal.log)

**Comment by Michelangelos** [comment]
Ah I do not have Epic configured but I can confirm the exact same issue with Steam, no games are listed... and same version !

**Comment by Raicuparta** [comment]
Please disable Steam beta for now, that's what's causing this. Next Rai Pal update will fix it.

**Comment by Bassquake** [comment]
Yep. Reverting to normal works now. Didnt even know I was on beta. For those that needs to revert to normal:

- In Steam, click Steam at top left.
- Click Interface on left panel.
- Change dropdown in Client Beta Participation to No Beta Chosen.
- Restart Steam.

**Comment by Raicuparta** [comment]
Fixed in Rai Pal 0.12.1

**Comment by njozsef** [comment]
Still "steam-beta interface" issue on v 0.14.0
