### ISSUE TITLE
program doesnt stop loading

### ISSUE THREAD

**Issue by war2die4** [Raicuparta/rai-pal#226]
When it startsthe refresh button just keeps spinning forever, it doesnt show all installed games, the owned tab i think shows all games i own but doesnt show any engines, and mods tab doesnt show the recent mods
heres my log
[Rai Pal.log](https://github.com/user-attachments/files/16255063/Rai.Pal.log)

**Comment by Raicuparta** [comment]
I'm guessing you have a large game library on Steam? The next update should fix this.

**Comment by war2die4** [comment]
Yeah i do, thanks for reply.
