### ISSUE TITLE
[Feature] Run Meta Quest Link if it's not running before running a modded game

### ISSUE THREAD

**Issue by Bardo-Konrad** [Raicuparta/rai-pal#227]
See title.

**Comment by Raicuparta** [comment]
Out of scope for Rai Pal, could maybe be a thing that mods like UUVR or UEVR do, but I doubt anyone would ever want to implement such a specific thing.

**Comment by Bardo-Konrad** [comment]
Meta Quest Link must run for the Quest 2 to work with Rai Pal.
