### ISSUE TITLE
Failed to get app updates on Windows

### ISSUE THREAD

**Issue by tufeixp** [Raicuparta/rai-pal#247]
: Command plugin:updater|download_and_install not allowed by ACL

**Comment by Raicuparta** [comment]
Hey. Is this still happening?

**Comment by tufeixp** [comment]
Looks like the error has gone by using vpn with v.0.14.0, but uevr v1.04 upgrade reports some error like "Failed to execute command: Error: "error sending request for url (https://github.com/praydog/UEVR/releases/download...", or report harm by windows defender.
