### ISSUE TITLE
Previous Install was on G:

### ISSUE THREAD

**Issue by FFXKevin** [Raicuparta/rai-pal#249]
The installer chokes on me when running it:
![image](https://github.com/user-attachments/assets/4ec44af5-9087-4c43-adac-28db983bc749)

A way to change it would be excellent.

**Comment by Raicuparta** [comment]
Could you uninstall the previous install of Rai Pal and then try installing it again?

**Comment by Raicuparta** [comment]
The installer isn't really something I have full control over so not much I can do about this 🤷

**Comment by xypherorion** [comment]
The fix is to delete this key in RegEdit:
Computer\HKEY_CURRENT_USER\SOFTWARE\raicuparta

**Comment by xypherorion** [comment]
I'd also suggest putting in a patch request with your installer software developers.
